os: linux
dist: xenial
language: cpp
compiler: gcc
env:
  global:
    - APP_ID=inputstream.adaptive.testing
    - secure: "dDCBAlMBg+/rjsL994f8GcL1exlIKm+n8qAG9lY1S/ye/Pc7jqIJavRl4/omiQ3xDI/8dmmwM0j6nhPrHaBVAlcpiyG8KCi/wl6jD5c6hT+f1BMMy/J4T0Ywn+AsgGXpLuyOqXzmFFHQAWHuosZaSfjzXkQAIlLGvlYYXMtFNIp2wX5RRPaImmYzWA626SgUteGtgapiL6JEnCRNqxzVUH7LFz1CP6Qjgq7MQWog5mazUG8EZp519PAjHIQOK6UvgUxtDSYddl4pGh6YQi5P4w92KUBUBYycqQ+dDWBwCPBBsvr/LKKumRFLYKGf0FaMw02qgAXj1pjpnCpmBjANjqzQWXnb9hzgDmqjRSQ7/9KJM65mbF4K3E5WXDuBoSWxupkAMMFQzzGLPQOsMai5dMS0lVw2FVnnGlxGYGaJ6LQmqhJ7V/pLUcivtK+sJChex4RP6kNLlvMZ97YihwCu2AhxqMtOPyy9YsoMFKrJKSEpOJcDcCcD8/HmBMTZGc9uIu77NWBs7vr9Lb9sJ9l1q7ma0zjBauC3vRG1jMQi+jZ0Yc7H7CWIvmHScmAKN5wjO4+wLjHf+mx5WFvKHM3X6jpCz+f33thanfAAeyZ7IJuwemP/hQsr1zrUL+fT0/96S7cYXjgabnXnKLFLNkeCWYS0R1aCDSPk4+nxptbJLFE="

jobs:
  include:
    - stage: compile
      before_script:
        - sudo apt install -y --no-install-recommends crossbuild-essential-arm64
      env: PLATFORM="linux" ARCH="aarch64" KODI_VERSION="leia"
      workspaces:
        create:
          name: linux-aarch64-leia
          paths: $HOME/zips
    - env: PLATFORM="linux" ARCH="aarch64" KODI_VERSION="matrix"
      before_script:
        - sudo apt install -y --no-install-recommends crossbuild-essential-arm64
      dist: bionic
      workspaces:
        create:
          name: linux-aarch64-matrix
          paths: $HOME/zips
          
    - env: PLATFORM="linux" ARCH="armv7" KODI_VERSION="leia"
      before_script:
        - sudo apt install -y --no-install-recommends crossbuild-essential-armhf
      workspaces:
        create:
          name: linux-armv7-leia
          paths: $HOME/zips
    - env: PLATFORM="linux" ARCH="armv7" KODI_VERSION="matrix"
      before_script:
        - sudo apt install -y --no-install-recommends crossbuild-essential-armhf
      dist: bionic
      workspaces:
        create:
          name: linux-armv7-matrix
          paths: $HOME/zips

    - env: PLATFORM="linux" ARCH="x86_64" KODI_VERSION="leia"
      workspaces:
        create:
          name: linux-x86_64-leia
          paths: $HOME/zips
    - env: PLATFORM="linux" ARCH="x86_64" KODI_VERSION="matrix"
      dist: bionic
      workspaces:
        create:
          name: linux-x86_64-matrix
          paths: $HOME/zips

    - env: PLATFORM="android" ARCH="aarch64" KODI_VERSION="leia"
      workspaces:
        create:
          name: android-aarch64-leia
          paths: $HOME/zips
    - env: PLATFORM="android" ARCH="aarch64" KODI_VERSION="matrix"
      dist: bionic
      workspaces:
        create:
          name: android-aarch64-matrix
          paths: $HOME/zips
    
    - env: PLATFORM="android" ARCH="armv7" KODI_VERSION="leia"
      workspaces:
        create:
          name: android-armv7-leia
          paths: $HOME/zips
    - env: PLATFORM="android" ARCH="armv7" KODI_VERSION="matrix"
      dist: bionic
      workspaces:
        create:
          name: android-armv7-matrix
          paths: $HOME/zips
    
    - env: PLATFORM="darwin" ARCH="x86_64" KODI_VERSION="leia"
      os: osx
      osx_image: xcode11.3
      before_cache:
        - brew cleanup
      cache:
        directories:
          - $HOME/Library/Caches/Homebrew
          - /usr/local/Homebrew
      addons:
        homebrew:
          packages:
          - aria2
          - gnu-getopt
          - gnu-sed
          - bash
          - coreutils
      install:
        - echo 'export PATH="/usr/local/opt/gnu-getopt/bin:$PATH"' >> ~/.bash_profile && . ~/.bash_profile
        - pip3 install gitpython
        - git clone https://github.com/johnny5-is-alive/iat-repo.git $HOME/.deploy
      workspaces:
        create:
          name: darwin-x86_64-leia
          paths: $HOME/zips
    - env: PLATFORM="darwin" ARCH="x86_64" KODI_VERSION="matrix"
      os: osx
      osx_image: xcode11.3
      before_cache:
        - brew cleanup
      cache:
        directories:
          - $HOME/Library/Caches/Homebrew
          - /usr/local/Homebrew
      addons:
        homebrew:
          packages:
          - aria2
          - gnu-getopt
          - gnu-sed
          - bash
          - coreutils
      install:
        - echo 'export PATH="/usr/local/opt/gnu-getopt/bin:$PATH"' >> ~/.bash_profile && . ~/.bash_profile
        - pip3 install gitpython
        - git clone https://github.com/johnny5-is-alive/iat-repo.git $HOME/.deploy
      workspaces:
        create:
          name: darwin-x86_64-matrix
          paths: $HOME/zips
    
    - env: PLATFORM="windows" ARCH="x86" KODI_VERSION="leia"
      os: windows
      install: skip
      before_script:
        - export VS150COMNTOOLS="/c/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/Common7/Tools"
      workspaces:
        create:
          name: windows-x86-leia
          paths: $HOME/zips
    - env: PLATFORM="windows" ARCH="x86_64" KODI_VERSION="leia"
      os: windows
      install: skip
      before_script:
        - export VS150COMNTOOLS="/c/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/Common7/Tools"
      workspaces:
        create:
          name: windows-x86_64-leia
          paths: $HOME/zips
    - env: PLATFORM="windows" ARCH="x86_64" KODI_VERSION="matrix"
      os: windows
      install: skip
      before_script:
        - export VS150COMNTOOLS="/c/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/Common7/Tools"
      workspaces:
        create:
          name: windows-x86_64-matrix
          paths: $HOME/zips
    

    - stage: deploy-main-android-windows
      if: tag IS present
      language: python
      workspaces:
        use:
          - android-aarch64-leia
          - android-aarch64-matrix
          - android-armv7-leia
          - android-armv7-matrix
          - windows-x86-leia
          - windows-x86_64-leia
          - windows-x86_64-matrix
      install:
        - pip3 install gitpython
        - git clone https://github.com/johnny5-is-alive/iat-repo.git $HOME/.deploy
      script:
        - mv $TRAVIS_BUILD_DIR/C:/Users/travis/zips/*.zip $HOME/zips
        - bash -x $TRAVIS_BUILD_DIR/build_scripts/deploy.sh -k leia -r main
        - bash -x $TRAVIS_BUILD_DIR/build_scripts/deploy.sh -k matrix -r main
    
    - stage: deploy-main-macos
      if: tag IS present
      os: osx
      osx_image: xcode11.3
      before_cache:
        - brew cleanup
      cache:
        directories:
          - $HOME/Library/Caches/Homebrew
          - /usr/local/Homebrew
      addons:
        homebrew:
          packages:
          - gnu-getopt
          - bash
          - coreutils
      install:
        - echo 'export PATH="/usr/local/opt/gnu-getopt/bin:$PATH"' >> ~/.bash_profile && . ~/.bash_profile
        - pip3 install gitpython
        - git clone https://github.com/johnny5-is-alive/iat-repo.git $HOME/.deploy
      language: shell
      workspaces:
        use:
          - darwin-x86_64-leia
          - darwin-x86_64-matrix
      script:
        - bash -x $TRAVIS_BUILD_DIR/build_scripts/deploy.sh -k leia -r main
        - bash -x $TRAVIS_BUILD_DIR/build_scripts/deploy.sh -k matrix -r main
    
    - stage: deploy-linux-aarch64
      if: tag IS present
      language: python
      workspaces:
        use:
          - linux-aarch64-leia
          - linux-aarch64-matrix
      install:
        - pip3 install gitpython
        - git clone https://github.com/johnny5-is-alive/iat-repo.git $HOME/.deploy
      script:
        - bash -x $TRAVIS_BUILD_DIR/build_scripts/deploy.sh -k leia -r linux-aarch64
        - bash -x $TRAVIS_BUILD_DIR/build_scripts/deploy.sh -k matrix -r linux-aarch64
    
    - stage: deploy-linux-armv7
      if: tag IS present
      language: python
      workspaces:
        use:
          - linux-armv7-leia
          - linux-armv7-matrix
      install:
        - pip3 install gitpython
        - git clone https://github.com/johnny5-is-alive/iat-repo.git $HOME/.deploy
      script:
        - bash -x $TRAVIS_BUILD_DIR/build_scripts/deploy.sh -k leia -r linux-armv7
        - bash -x $TRAVIS_BUILD_DIR/build_scripts/deploy.sh -k matrix -r linux-armv7
    
    - stage: deploy-linux-x86_64
      if: tag IS present
      language: python
      workspaces:
        use:
          - linux-x86_64-leia
          - linux-x86_64-matrix
      install:
        - pip3 install gitpython
        - git clone https://github.com/johnny5-is-alive/iat-repo.git $HOME/.deploy
      script:
        - bash -x $TRAVIS_BUILD_DIR/build_scripts/deploy.sh -k leia -r linux-x86_64
        - bash -x $TRAVIS_BUILD_DIR/build_scripts/deploy.sh -k matrix -r linux-x86_64
        - cd $HOME/.deploy
        - git checkout master
        - git merge travis-build-$TRAVIS_BUILD_NUMBER
        - git push origin --delete travis-build-$TRAVIS_BUILD_NUMBER
        - git push --set-upstream origin master

install:
  - sudo apt-get update && sudo apt-get -y update
  - sudo apt install -y --no-install-recommends build-essential git cmake unzip aria2 default-jdk python3

script:
  - shopt -s expand_aliases
  - '[[ $TRAVIS_OS_NAME = "osx" ]] && alias bsh="/usr/local/bin/bash" && export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH" || alias bsh="/bin/bash"'
  - bsh -x $TRAVIS_BUILD_DIR/build_scripts/build-ia.sh
    --kodiversion $KODI_VERSION
    --no-apt-install
    --arch $ARCH 
    --platform $PLATFORM
  - mkdir -p $HOME/zips  
  - mv $HOME/*.zip $HOME/zips  
